const fixedPath = '../assets/images';

const images = {
    telephone: require(`${fixedPath}/telephone.png`),
    user: require(`${fixedPath}/user.png`),
    email: require(`${fixedPath}/email.png`),
    eye: require(`${fixedPath}/eye.png`),
    eye_off: require(`${fixedPath}/eye_off.png`),
    birthday: require(`${fixedPath}/birthday.png`),
    lock: require(`${fixedPath}/accountPrivacy.png`),
    calendar: require(`${fixedPath}/calendar.png`),
    setting: require(`${fixedPath}/setting.png`),
    plus: require(`${fixedPath}/plus.png`),
    send: require(`${fixedPath}/send.png`),
    back: require(`${fixedPath}/back.png`),
    camera: require(`${fixedPath}/camera.png`),
    qrCode: require(`${fixedPath}/qrCode.png`),
    reply: require(`${fixedPath}/reply.png`),
    forward: require(`${fixedPath}/forward.png`),
    copy: require(`${fixedPath}/copy.png`),
    star: require(`${fixedPath}/star.png`),
    edit: require(`${fixedPath}/edit.png`),
    deleteIcon: require(`${fixedPath}/deleteIcon.png`),
    threeDots: require(`${fixedPath}/threeDots.png`),
    delete: require(`${fixedPath}/delete.png`),
    pinNot: require(`${fixedPath}/pinNot.png`),
    searchInterfaceSymbol: require(`${fixedPath}/search-interface-symbol.png`),
    newChat: require(`${fixedPath}/newChat.png`),
    newGroup: require(`${fixedPath}/newGroup.png`),
    newAnnouncement: require(`${fixedPath}/newAnnouncement.png`),
    bell: require(`${fixedPath}/bell.png`),
    mic: require(`${fixedPath}/mic.png`),
    stop: require(`${fixedPath}/stop.png`),
    group: require(`${fixedPath}/group.png`),
    search: require(`${fixedPath}/search.png`),
    calling: require(`${fixedPath}/calling.png`),
    videoCamera: require(`${fixedPath}/videoCamera.png`),
    homeMore: require(`${fixedPath}/HomeMore.png`),
    audio: require(`${fixedPath}/audio.png`),
    add: require(`${fixedPath}/add.png`),
}

export { images };